name: 🐞 Bug Report
description: Create a report to help us improve the app
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for reporting an issue!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How much does this affect the user experience?
      options:
        - 🔴 Critical (Crash / Data Loss)
        - 🟠 Major (Feature Broken)
        - 🟡 Minor (Annoyance / Glitch)
        - ⚪ Trivial (Typo / UI Polish)
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Numbered steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
      placeholder: |
        it should have done x, y, z
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behaviour
      description: What actually happened?
      placeholder: |
        It only did x and y
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform / OS
      description: Which platform were you using?
      options:
        - iOS
        - Android
        - Web App
        - Desktop
      multiple: true
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version number is displayed in settings? (e.g., 1.0.4)
      placeholder: x.x.x
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or Logs
      description: Drag and drop screenshots or paste logs here.
    validations:
      required: false
